# Generated by Django
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyclonePredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyclone_name', models.CharField(default='CYCLONE DANA (BOB-02)', max_length=120)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latitude', models.FloatField(default=15.4)),
                ('longitude', models.FloatField(default=87.2)),
                ('probability_score', models.FloatField(help_text='Intensification Probability (0.0% to 100.0%)')),
                ('risk_level', models.CharField(default='CRITICAL INTENSIFICATION', max_length=80)),
                ('risk_badge', models.CharField(default='CRITICAL', max_length=40)),
                ('geographic_alert', models.TextField(default='Immediate evacuation dispatch advised for coastal sectors.')),
                ('satellite_file', models.CharField(default='3RIMG_01JAN2024_2315_L1B_STD_V01R00.h5', max_length=255)),
                ('central_pressure_hpa', models.FloatField(default=962.0)),
                ('max_wind_speed_kmh', models.FloatField(default=175.0)),
                ('temperature_celsius', models.FloatField(default=28.6)),
                ('relative_humidity', models.FloatField(default=94.0)),
                ('model_version', models.CharField(default='MultiModal-CNN-LSTM-v1.0 (Spatial CNN + Temporal LSTM)', max_length=100)),
                ('raw_payload_json', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cyclone Prediction Record',
                'verbose_name_plural': 'Cyclone Prediction Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
