"""
Django settings for core project with Multi-Language Support (i18n).

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e(hd+gc01xxhmhq!z(96x-eu#4)(edbr$4%we_%$a73%6wtllc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'viewer',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Multi-language Locale Middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',  # i18n Context Processor
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# Internationalization (i18n) & Coastal Languages Configuration
# Primary Coastal Languages for Indian Cyclones: English, Hindi, Bengali, Odia
# ==============================================================================

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('hi', _('Hindi')),
    ('bn', _('Bengali')),
    ('or', _('Odia')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# ==============================================================================
# TERMINAL COMMANDS FOR GENERATING & COMPILING TRANSLATIONS (.po / .mo FILES):
# 
# 1. Generate translation message catalogs for Hindi, Bengali, and Odia:
#    django-admin makemessages -l hi
#    django-admin makemessages -l bn
#    django-admin makemessages -l or
#
# 2. Or using python manage.py:
#    python manage.py makemessages -l hi -l bn -l or
#
# 3. Edit translated text in:
#    locale/hi/LC_MESSAGES/django.po
#    locale/bn/LC_MESSAGES/django.po
#    locale/or/LC_MESSAGES/django.po
#
# 4. Compile message catalogs into binary .mo files:
#    django-admin compilemessages
#    (or: python manage.py compilemessages)
# ==============================================================================


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
